#!/usr/bin/env bash
# Convert Shadowrocket module rules to AdGuard Home DNS filter syntax (*.agh.txt)
# and generate the iOS DoT profile.
# Rule mapping:
#   DOMAIN/DOMAIN-SUFFIX -> ||domain^
#   DOMAIN-KEYWORD       -> bare keyword (substring match)
#   IP-CIDR              -> skipped (cannot be blocked at the DNS layer)
set -euo pipefail
cd "$(dirname "$0")/.."

to_agh() {
  awk -F, '
    /^#!/ { next }
    /^#/ { line=$0; sub(/^#/, "!", line); print line; next }
    /^DOMAIN-KEYWORD,/ { print $2; next }
    /^DOMAIN,/ { print "||" $2 "^"; next }
    /^DOMAIN-SUFFIX,/ { print "||" $2 "^"; next }
  ' "$1"
}

{
  echo '! Auto-generated by factory/build_agh.sh, do not edit manually'
  echo '! Source: custom_reject_list.module (Cowjiang/cowjiang-adguard)'
  to_agh rules/custom_reject_list.module
} > dist/agh_custom_reject.txt

{
  echo '! Auto-generated by factory/build_agh.sh, do not edit manually'
  echo '! Source: sr_reject_list.module (GMOogway/shadowrocket-rules)'
  to_agh upstream/sr_reject_list.module
} > dist/agh_sr_reject.txt

echo "dist/agh_custom_reject.txt: $(grep -c '^[^!]' dist/agh_custom_reject.txt) rules"
echo "dist/agh_sr_reject.txt: $(grep -c '^[^!]' dist/agh_sr_reject.txt) rules"

# Generate the iOS DoT profile (CI keeps this file in sync when config changes).
# Fixed UUIDs so the file content stays stable unless the config actually changes.
UUID1="7A3F2C91-5E84-4D6B-9A12-C3D8F0E51B47"
UUID2="B8D6E204-91A7-4F35-8C29-D1E6A7B30F58"
cat > dist/Cowjiang-AdGuard.mobileconfig <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>PayloadContent</key>
	<array>
		<dict>
			<key>DNSSettings</key>
			<dict>
				<key>DNSProtocol</key>
				<string>TLS</string>
				<key>ServerName</key>
				<string>dns.inceptae.com</string>
			</dict>
			<key>PayloadDescription</key>
			<string>https://github.com/Cowjiang</string>
			<key>PayloadDisplayName</key>
			<string>Cowjiang AdGuard</string>
			<key>PayloadIdentifier</key>
			<string>com.apple.dnsSettings.managed.dns.inceptae.dot</string>
			<key>PayloadOrganization</key>
			<string>Cowjiang</string>
			<key>PayloadType</key>
			<string>com.apple.dnsSettings.managed</string>
			<key>PayloadUUID</key>
			<string>$UUID1</string>
			<key>PayloadVersion</key>
			<integer>1</integer>
			<key>ProhibitDisablement</key>
			<false/>
		</dict>
	</array>
	<key>PayloadDescription</key>
	<string>Cowjiang AdGuard — 加密 DNS (DoT) 广告过滤，规则每日自动更新</string>
	<key>PayloadDisplayName</key>
	<string>Cowjiang AdGuard</string>
	<key>PayloadIdentifier</key>
	<string>inceptae.dot.profile</string>
	<key>PayloadOrganization</key>
	<string>Cowjiang</string>
	<key>PayloadRemovalDisallowed</key>
	<false/>
	<key>PayloadType</key>
	<string>Configuration</string>
	<key>PayloadUUID</key>
	<string>$UUID2</string>
	<key>PayloadVersion</key>
	<integer>1</integer>
</dict>
</plist>
EOF
echo "dist/Cowjiang-AdGuard.mobileconfig: generated"
