#!name=custom_reject_list
#!homepage=https://github.com/Cowjiang/shadowrocket-rules
#!desc=Custom reject list
[Rule]
# 墨迹天气
DOMAIN-KEYWORD,me.api.moji.com,REJECT
DOMAIN-KEYWORD,android.bugly.qq.com,REJECT
DOMAIN-KEYWORD,av1.xdrig.com,REJECT
DOMAIN-KEYWORD,adash.man.aliyuncs.com,REJECT
DOMAIN,ad.api.moji.com,REJECT
DOMAIN,adlaunch.moji.com,REJECT
DOMAIN,ads.mojicdn.com,REJECT
DOMAIN,v1.log.moji.com,REJECT
DOMAIN-SUFFIX,cdn.moji.com,REJECT
DOMAIN-SUFFIX,fds.api.moji.com,REJECT
DOMAIN-SUFFIX,app.moji001.com,REJECT
DOMAIN-SUFFIX,ugc.moji001.com,REJECT
DOMAIN-SUFFIX,cdn.moji002.com,REJECT
DOMAIN-SUFFIX,cdn2.moji002.com,REJECT
DOMAIN-SUFFIX,mme.api.moji.com,REJECT
DOMAIN-SUFFIX,errnewlog.umeng.com,REJECT
# 微信小程序
DOMAIN,wxsnsdy.wxs.qq.com,REJECT
DOMAIN,wxsmsdy.video.qq.com,REJECT
DOMAIN,wxsnsdythumb.wxs.qq.com,REJECT
DOMAIN,ads-shopping.shouqianba.com,REJECT
DOMAIN,ad.maoyan.com,REJECT
DOMAIN,e.jparking.cn,REJECT
# 彩云天气
DOMAIN,ad.cyapi.cn,REJECT
# 中国电信
DOMAIN,ad.21cn.com,REJECT
DOMAIN,ad.k.21cn.com,REJECT
DOMAIN,admarket.21cn.com,REJECT
DOMAIN,adshows.21cn.com,REJECT
IP-CIDR,122.229.8.47/32,REJECT,no-resolve
IP-CIDR,122.229.29.89/32,REJECT,no-resolve

[URL Rewrite]
^https?://cloud\.189\.cn/include/splash/ - reject

[Map Local]
^https?://zt-app\.go189\.cn/zt-app/welcome/.*?Animation status-code=200

[MITM]
hostname = %APPEND% cloud.189.cn, zt-app.go189.cn